openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Validations API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: Validations
paths:
  /Validations.svc/json/GetAll:
    post:
      tags:
      - Validations
      description: Retrieves rules and mappings of validations.
      operationId: GetAll
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllValidationsResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Get all
      x-summary-source: derived
components:
  schemas:
    ValidationMappingRef:
      type: object
      properties:
        Name:
          type: string
        Rules:
          type: object
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    ValidationRule:
      type: object
      properties:
        Name:
          type: string
        MinValue:
          type: number
          format: double
        MinValueMessage:
          type: string
        MaxValue:
          type: number
          format: double
        MaxValueMessage:
          type: string
        MinLength:
          type: integer
          format: int32
        MinLengthMessage:
          type: string
        MaxLength:
          type: integer
          format: int32
        MaxLengthMessage:
          type: string
        Required:
          type: boolean
        RequiredMessage:
          type: string
        DisplayName:
          type: string
        Extend:
          type: string
        Overrides:
          type: object
        Precision:
          type: integer
          format: int32
        RequiresPrecision:
          type: boolean
        RequiresPrecisionMessage:
          type: string
        FormatMessage:
          type: string
        CharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
    AllValidationsResponse:
      type: object
      properties:
        Rules:
          type: array
          items:
            $ref: '#/components/schemas/ValidationRule'
        Mappings:
          type: array
          items:
            $ref: '#/components/schemas/ValidationMappingRef'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
