openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Google API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: Google
paths:
  /Google.svc/json/Connected:
    post:
      tags:
      - Google
      description: Returns if Google Calendar is connected or not for specified user.
      operationId: Connected
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetGoogleConnectionStatusResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Connected
      x-summary-source: derived
  /Google.svc/json/SyncCalendar:
    post:
      tags:
      - Google
      description: Syncs Google Calendar for current user.
      operationId: SyncCalendar
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Sync calendar
      x-summary-source: derived
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    GetGoogleConnectionStatusResponse:
      type: object
      properties:
        CalendarConnected:
          type: boolean
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
