openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Document Templates API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: DocumentTemplates
  description: Document template operations.
paths:
  /DocumentTemplates.svc/json/GetDocumentTemplates:
    post:
      tags:
      - DocumentTemplates
      description: Get document template by name or tags for merging.
      operationId: GetDocumentTemplates
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDocumentTemplatesResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDocumentTemplatesRequest'
        required: true
      summary: Get document templates
      x-summary-source: derived
  /DocumentTemplates.svc/json/DeleteDocumentTemplate:
    post:
      tags:
      - DocumentTemplates
      description: Delete a specific document template.
      operationId: DeleteDocumentTemplate
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteDocumentTemplateResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteDocumentTemplateRequest'
        required: true
      summary: Delete document template
      x-summary-source: derived
components:
  schemas:
    GetDocumentTemplatesResponse:
      type: object
      properties:
        DocumentTemplates:
          type: array
          items:
            $ref: '#/components/schemas/DocumentTemplate'
        Count:
          type: integer
          format: int32
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    DocumentTemplate:
      type: object
      properties:
        Title:
          type: string
        UploadedByUserId:
          type: integer
          format: int32
        UploadedByUserName:
          type: string
        FileUrl:
          type: string
        IsValidated:
          type: boolean
        Size:
          type: integer
          format: int32
        Tags:
          type: array
          items:
            type: string
        ID:
          type: integer
          format: int32
    DeleteDocumentTemplateResponse:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    DeleteDocumentTemplateRequest:
      type: object
      properties:
        DocumentTemplateId:
          type: integer
          format: int32
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    GetDocumentTemplatesRequest:
      type: object
      properties:
        Offset:
          type: integer
          format: int32
        Fetch:
          type: integer
          format: int32
        Tags:
          type: array
          items:
            type: string
        Search:
          type: string
        SortByTitle:
          type: boolean
        SortDescending:
          type: boolean
        GetCount:
          type: boolean
        State:
          type: string
          enum:
          - None
          - Valid
          - NotValid
