openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Tags API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: Tags
  description: Tags can be attached to contacts, documents, matters and events in order to group, sort, and find related items.
paths:
  /Tags.svc/json/Search:
    post:
      tags:
      - Tags
      description: Search for all items with a specific tag.
      operationId: Search
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchTagsResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchTagsRequest'
        required: true
      summary: Search
      x-summary-source: derived
  /Tags.svc/json/AddTag:
    post:
      tags:
      - Tags
      description: Create a new tag for a specific item.
      operationId: AddTag
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddRemoveTagResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRemoveTagRequest'
        required: true
      summary: Add tag
      x-summary-source: derived
  /Tags.svc/json/RemoveTag:
    post:
      tags:
      - Tags
      description: Remove a tag for a specific item.
      operationId: RemoveTag
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddRemoveTagResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRemoveTagRequest'
        required: true
      summary: Remove tag
      x-summary-source: derived
components:
  schemas:
    SearchTagsRequest:
      type: object
      properties:
        SearchText:
          type: string
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    AddRemoveTagResponse:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    AddRemoveTagRequest:
      type: object
      properties:
        Tag:
          type: object
          $ref: '#/components/schemas/Tag'
        EntityTypeId:
          type: string
          enum:
          - None
          - Contact
          - User
          - Matter
          - Document
          - Note
          - Activity
          - CalendarEntry
          - TodoItem
          - LedgerEntry
          - Expense
          - BilledTime
          - Timer
          - PhoneMessage
          - MatterTrustLedgerEntry
          - ClientTrustLedgerEntry
          - DocumentTemplate
          - Email
          - Portal
          - FlatFee
          - ChatMessage
        EntityId:
          type: integer
          format: int32
    SearchTagsResponse:
      type: object
      properties:
        Tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    Tag:
      type: object
      properties:
        Name:
          type: string
        ID:
          type: integer
          format: int32
