openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Billing Tiers API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: BillingTiers
paths:
  /BillingTiers.svc/json/SaveBillingFeatureInterest:
    post:
      tags:
      - BillingTiers
      description: Saves billing feature for current install.
      operationId: SaveBillingFeatureInterest
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveBillingFeatureInterestResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveBillingFeatureInterestRequest'
        required: true
      summary: Save billing feature interest
      x-summary-source: derived
  /BillingTiers.svc/json/GetDefaultBillingTiers:
    post:
      tags:
      - BillingTiers
      description: Gets default tiers for current install.
      operationId: GetDefaultBillingTiers
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDefaultBillingTiersResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Get default billing tiers
      x-summary-source: derived
components:
  schemas:
    Install:
      type: object
      properties:
        Name:
          type: string
        VaultId:
          type: string
        InstallType:
          type: string
        InstallDate:
          type: string
          format: date-time
        BillingEndDate:
          type: string
          format: date-time
        RemovedDate:
          type: string
          format: date-time
        TotalUsers:
          type: integer
          format: int32
        IsDeleted:
          type: boolean
        Status:
          type: integer
          format: int32
        TrialTypeId:
          type: integer
          format: int32
        BillingFeatureInterests:
          type: object
        InstallScripts:
          type: object
        InstallSegments:
          type: object
        AccessTokens:
          type: object
        TenantContractConfigs:
          type: object
        InstallationsBilling:
          type: object
          $ref: '#/components/schemas/InstallationsBilling'
        TenantContractExpirationNotificationHistories:
          type: object
        TenantContractExpirationNotificationHistories1:
          type: object
        TenantContracts:
          type: object
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsSaved:
          type: boolean
    BillingFeatureInterest:
      type: object
      properties:
        InstallationId:
          type: integer
          format: int32
        FeatureId:
          type: integer
          format: int32
        InterestTypeId:
          type: integer
          format: int32
        Date:
          type: string
          format: date-time
        UserId:
          type: string
        BillingFeatureInterestType:
          type: object
          $ref: '#/components/schemas/BillingFeatureInterestType'
        BillingFeature:
          type: object
          $ref: '#/components/schemas/BillingFeature'
        Installation:
          type: object
          $ref: '#/components/schemas/Install'
        aspnet_Users:
          type: object
          $ref: '#/components/schemas/aspnet_Users'
        FeatureIdentifier:
          type: string
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsDeleted:
          type: boolean
        IsSaved:
          type: boolean
    aspnet_Membership:
      type: object
      properties:
        ApplicationId:
          type: string
        UserId:
          type: string
        Password:
          type: string
        PasswordFormat:
          type: integer
          format: int32
        PasswordSalt:
          type: string
        MobilePIN:
          type: string
        Email:
          type: string
        LoweredEmail:
          type: string
        PasswordQuestion:
          type: string
        PasswordAnswer:
          type: string
        IsApproved:
          type: boolean
        IsLockedOut:
          type: boolean
        CreateDate:
          type: string
          format: date-time
        LastLoginDate:
          type: string
          format: date-time
        LastPasswordChangedDate:
          type: string
          format: date-time
        LastLockoutDate:
          type: string
          format: date-time
        FailedPasswordAttemptCount:
          type: integer
          format: int32
        FailedPasswordAttemptWindowStart:
          type: string
          format: date-time
        FailedPasswordAnswerAttemptCount:
          type: integer
          format: int32
        FailedPasswordAnswerAttemptWindowStart:
          type: string
          format: date-time
        Comment:
          type: string
        aspnet_Users:
          type: object
          $ref: '#/components/schemas/aspnet_Users'
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsDeleted:
          type: boolean
        IsSaved:
          type: boolean
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    BillingTier:
      type: object
      properties:
        Id:
          type: integer
          format: int32
        Name:
          type: string
        MonthlyPrice:
          type: number
          format: double
        MonthlyPriceId:
          type: integer
          format: int32
        QuarterlyPrice:
          type: number
          format: double
        QuarterlyPriceId:
          type: integer
          format: int32
        YearlyPrice:
          type: number
          format: double
        YearlyPriceId:
          type: integer
          format: int32
        BiennialPrice:
          type: number
          format: double
        BiennialPriceId:
          type: integer
          format: int32
        IsCollapsed:
          type: boolean
        CreatedDate:
          type: string
          format: date-time
        UsedInSignup:
          type: boolean
        MaxNumberOfUsers:
          type: integer
          format: int32
        Description:
          type: string
        BillingFrequency:
          type: string
          enum:
          - Monthly
          - Yearly
          - TriAnnual
          - Quarterly
          - Biennial
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    GetDefaultBillingTiersResponse:
      type: object
      properties:
        Tiers:
          type: array
          items:
            $ref: '#/components/schemas/BillingTier'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    SaveBillingFeatureInterestRequest:
      type: object
      properties:
        FeatureInterest:
          type: object
          $ref: '#/components/schemas/BillingFeatureInterest'
    InstallationsBilling:
      type: object
      properties:
        InstallationId:
          type: integer
          format: int32
        LastInvoiceDate:
          type: string
          format: date-time
        LastPaymentReceived:
          type: string
          format: date-time
        Balance:
          type: number
          format: double
        Charge:
          type: number
          format: double
        BillingFrequency:
          type: integer
          format: int32
        StoreCreditBalance:
          type: number
          format: double
        SubscriptionPriceId:
          type: integer
          format: int32
        BillingTierId:
          type: integer
          format: int32
        BillingTier:
          type: object
          $ref: '#/components/schemas/BillingTier'
        Installation:
          type: object
          $ref: '#/components/schemas/Install'
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsDeleted:
          type: boolean
        IsSaved:
          type: boolean
    aspnet_Users:
      type: object
      properties:
        ApplicationId:
          type: string
        UserId:
          type: string
        UserName:
          type: string
        LoweredUserName:
          type: string
        MobileAlias:
          type: string
        IsAnonymous:
          type: boolean
        LastActivityDate:
          type: string
          format: date-time
        AccessTokens:
          type: object
        BillingFeatureInterests:
          type: object
        BillingTierAudits:
          type: object
        TwoFactorAuthenticationRecoveryCodes:
          type: object
        TwoFactorAuthenticationUsers:
          type: object
        UserRoles:
          type: object
        UsersAccesses:
          type: object
        aspnet_Membership:
          type: object
          $ref: '#/components/schemas/aspnet_Membership'
        TenantContracts:
          type: object
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsDeleted:
          type: boolean
        IsSaved:
          type: boolean
    BillingFeatureInterestType:
      type: object
      properties:
        Name:
          type: string
        BillingFeatureInterests:
          type: object
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsDeleted:
          type: boolean
        IsSaved:
          type: boolean
    BillingFeature:
      type: object
      properties:
        Name:
          type: string
        Description:
          type: string
        Identifier:
          type: string
        BillingModuleFeatures:
          type: object
        BillingFeatureInterests:
          type: object
        BillingTierIds:
          type: array
          items:
            type: integer
            format: int32
        Id:
          type: integer
          format: int32
        CreatedDate:
          type: string
          format: date-time
        LastModifiedDate:
          type: string
          format: date-time
        IsDeleted:
          type: boolean
        IsSaved:
          type: boolean
    SaveBillingFeatureInterestResponse:
      type: object
      properties:
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
