openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Time Options API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: TimeOptions
paths:
  /TimeOptions.svc/json/GetAll:
    post:
      tags:
      - TimeOptions
      description: Retrieves list of times in 15 minute increments. (12:00, 12:15, 12:30, etc..)
      operationId: GetAll
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeOptionsGetAllResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Get all
      x-summary-source: derived
  /TimeOptions.svc/json/GetNextTimes:
    post:
      tags:
      - TimeOptions
      description: Retrieves next available time in 15 minute increments with given current time.
      operationId: GetNextTimes
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeOptionsGetNextTimesResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeOptionsGetNextTimesRequest'
        required: true
      summary: Get next times
      x-summary-source: derived
components:
  schemas:
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    TimeOptionsGetNextTimesRequest:
      type: object
      properties:
        CurrentTime:
          type: string
    TimeOptionsGetAllResponse:
      type: object
      properties:
        Times:
          type: array
          items:
            $ref: '#/components/schemas/TimeOption'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    TimeOption:
      type: object
      properties:
        Time:
          type: string
        ID:
          type: integer
          format: int32
    TimeOptionsGetNextTimesResponse:
      type: object
      properties:
        Times:
          type: array
          items:
            $ref: '#/components/schemas/TimeOption'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
