openapi: 3.2.0
info:
  description: Welcome to the Rocket Matter API.
  version: '2.0'
  title: Rocket Matter Tax Rates API
  termsOfService: www.rocketmatter.com
  contact:
    email: developer@rocketmatter.com
  license:
    name: Rocket Matter
    url: www.rocketmatter.com
  x-logo:
    url: https://support.rocketmatter.com/wp-content/themes/rm-support/img/rm-logo.png
servers:
- url: https://<DOMAIN>/<INSTALL>/API_V2
tags:
- name: TaxRates
  description: Operations for managing tax rates.
paths:
  /TaxRates.svc/json/GetAll:
    post:
      tags:
      - TaxRates
      description: Get all tax rate configurations.
      operationId: GetAll
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxRatesGetAllResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Get all
      x-summary-source: derived
  /TaxRates.svc/json/Save:
    post:
      tags:
      - TaxRates
      description: Create a new tax rate, or update an existing tax rate.
      operationId: Save
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxRatesSaveResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxRatesSaveRequest'
        required: true
      summary: Save
      x-summary-source: derived
  /TaxRates.svc/json/Delete:
    post:
      tags:
      - TaxRates
      description: Delete a specific tax rate.
      operationId: Delete
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxRatesDeleteResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      summary: Delete
      x-summary-source: derived
  /TaxRates.svc/json/Search:
    post:
      tags:
      - TaxRates
      description: Search for tax rates by description.
      operationId: Search
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxRatesSearchResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxRatesSearchRequest'
        required: true
      summary: Search
      x-summary-source: derived
  /TaxRates.svc/json/Get:
    post:
      tags:
      - TaxRates
      description: Get all tax rate configurations.
      operationId: Get
      responses:
        '200':
          description: Successfully processed request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxRatesGetResponse'
        '400':
          description: Internal server error
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxRatesGetRequest'
        required: true
      summary: Get
      x-summary-source: derived
components:
  schemas:
    TaxRatesGetResponse:
      type: object
      properties:
        TaxRate:
          type: object
          $ref: '#/components/schemas/TaxRate'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    CharacterValidationRule:
      type: object
      properties:
        ShouldMatch:
          type: boolean
        Message:
          type: string
        Regex:
          type: string
    TaxRate:
      type: object
      properties:
        Id:
          type: string
        Description:
          type: string
        Rate:
          type: number
          format: double
        TaxRateType:
          type: string
          enum:
          - FeesAndExpenses
          - FeesAndSelectedExpenses
          - Expenses
          - SelectedExpenses
          - SelectedFees
          - SelectedFeesAndSelectedExpenses
        AppliedToMatter:
          type: boolean
    ValidationResult:
      type: object
      properties:
        MinValue:
          type: boolean
        MaxValue:
          type: boolean
        MinLength:
          type: boolean
        MaxLength:
          type: boolean
        Required:
          type: boolean
        PropertyDisplayName:
          type: string
        Precision:
          type: boolean
        ValueEntered:
          type: object
        Name:
          type: string
        ObjectName:
          type: string
        ExternalID:
          type: string
        MinValueMessage:
          type: string
        MaxValueMessage:
          type: string
        MinLengthMessage:
          type: string
        MaxLengthMessage:
          type: string
        RequiredMessage:
          type: string
        RequiredPrecisionMessage:
          type: string
        BaseFailureMessage:
          type: string
        FailedValidationMessages:
          type: array
          items:
            type: string
        FailedCharacterValidations:
          type: array
          items:
            $ref: '#/components/schemas/CharacterValidationRule'
        IsValid:
          type: boolean
    TaxRatesGetRequest:
      type: object
      properties:
        TaxRateId:
          type: string
        TaxRateDescription:
          type: string
    TaxRatesGetAllResponse:
      type: object
      properties:
        TaxRates:
          type: array
          items:
            $ref: '#/components/schemas/TaxRate'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    TaxRatesSaveRequest:
      type: object
      properties:
        TaxRate:
          type: object
          $ref: '#/components/schemas/TaxRate'
    TaxRatesSearchRequest:
      type: object
      properties:
        SearchText:
          type: string
    TaxRatesDeleteResponse:
      type: object
      properties:
        TaxRate:
          type: object
          $ref: '#/components/schemas/TaxRate'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    TaxRatesSaveResponse:
      type: object
      properties:
        TaxRate:
          type: object
          $ref: '#/components/schemas/TaxRate'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
    TaxRatesSearchResponse:
      type: object
      properties:
        TaxRates:
          type: array
          items:
            $ref: '#/components/schemas/TaxRate'
        Success:
          type: boolean
        Message:
          type: string
        ErrorMessage:
          type: string
        ErrorNumber:
          type: integer
          format: int32
        FailedValidations:
          type: array
          items:
            $ref: '#/components/schemas/ValidationResult'
        Errors:
          type: array
          items:
            type: string
